### ISSUE TITLE
FlywayInitializer compilation error

### ISSUE THREAD

**Issue by frobian21** [DevQAC/QA-Portal#9]
#ERROR: cannot drop table training.qa_user because other objects depend on it.

Use DROP ... CASCADE to drop the dependent objects too.

qa-portal-services\core-api\target\classes\db\migration\V1_1__Core_DDL.sql
Line 17.
**Change** 
drop table if exists training.qa_user 
**To**
drop table if exists training.qa_user CASCADE
![Capture](https://user-images.githubusercontent.com/49647154/61790979-896f6700-ae10-11e9-9a3c-5a8ce74b4301.PNG)

**Comment by phtb233** [comment]
![Screenshot from 2019-07-25 11-13-13](https://user-images.githubusercontent.com/3501316/61866618-68208080-aecd-11e9-9149-4d21eb4fdfbd.png)
Now the migration files are complaining that the 'training' schema doesn't exist. Fixed it by adding:
![Screenshot from 2019-07-25 11-15-55](https://user-images.githubusercontent.com/3501316/61866724-99994c00-aecd-11e9-8185-ae104d593c32.png)

**Comment by phtb233** [comment]
![Screenshot from 2019-07-26 00-28-51](https://user-images.githubusercontent.com/3501316/61915456-6c37b700-af3c-11e9-9d99-ebd4ec41512c.png)
Two primary keys are given the same value (of 5). Also, the category field is not null, but isn't specified here. Finally, had to add spring.flyway.baseline-on-migrate= true in the application.yml files  to get flyway to start.
